#!/usr/bin/env python3
"""Open an inference PLY point cloud with Open3D.

This viewer is self-contained for the PLYs generated by tools/write_infer_ply.py.
For custom vertex fields such as semantic_pred, instance_pred, and score, it
reads the vertex table directly and builds an Open3D point cloud.
"""

from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np


CATEGORICAL_FIELDS = {
    "semantic_pred",
    "instance_pred",
    "semantic_gt",
    "instance_gt",
    "semantic_seg",
    "treeID",
}

PLY_SCALAR_TYPES = {
    "char": "i1",
    "int8": "i1",
    "uchar": "u1",
    "uint8": "u1",
    "short": "i2",
    "int16": "i2",
    "ushort": "u2",
    "uint16": "u2",
    "int": "i4",
    "int32": "i4",
    "uint": "u4",
    "uint32": "u4",
    "float": "f4",
    "float32": "f4",
    "double": "f8",
    "float64": "f8",
}

AUTO_COLOR_PRIORITY = (
    "red_green_blue",
    "instance_pred",
    "treeID",
    "semantic_pred",
    "score",
    "semantic_seg",
    "intensity",
    "z",
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Open a PLY point cloud in Open3D.")
    parser.add_argument(
        "ply",
        nargs="?",
        type=Path,
        default=Path("sample_data/new_sample_seg.ply"),
        help="PLY file to open. Defaults to sample_data/new_sample_seg.ply.",
    )
    parser.add_argument(
        "--color-by",
        default="auto",
        help=(
            "Color source: auto, none, z, intensity, semantic_pred, instance_pred, "
            "or any numeric vertex field."
        ),
    )
    parser.add_argument(
        "--point-size",
        type=float,
        default=2.0,
        help="Visualizer point size. Defaults to 2.0.",
    )
    parser.add_argument(
        "--voxel-size",
        type=float,
        default=0.0,
        help="Optional Open3D voxel downsample size for display only.",
    )
    parser.add_argument(
        "--list-fields",
        action="store_true",
        help="Print vertex fields and exit without opening a window.",
    )
    return parser.parse_args()


def parse_ply_header(path: Path) -> dict:
    with path.open("rb") as f:
        first = f.readline()
        if first.strip() != b"ply":
            raise ValueError(f"{path} is not a PLY file")

        fmt = None
        vertex_count = None
        vertex_properties = []
        current_element = None

        while True:
            line_bytes = f.readline()
            if not line_bytes:
                raise ValueError(f"{path} ended before end_header")
            line = line_bytes.decode("ascii").strip()

            if line == "end_header":
                header_size = f.tell()
                break
            if not line or line.startswith("comment"):
                continue

            parts = line.split()
            if parts[0] == "format":
                fmt = parts[1]
            elif parts[0] == "element":
                current_element = parts[1]
                if current_element == "vertex":
                    vertex_count = int(parts[2])
            elif parts[0] == "property" and current_element == "vertex":
                if parts[1] == "list":
                    raise ValueError(
                        "List properties in the vertex element are not supported")
                if parts[1] not in PLY_SCALAR_TYPES:
                    raise ValueError(f"Unsupported PLY property type: {parts[1]}")
                vertex_properties.append((parts[2], parts[1]))

    if fmt not in {"ascii", "binary_little_endian", "binary_big_endian"}:
        raise ValueError(f"Unsupported PLY format: {fmt}")
    if vertex_count is None:
        raise ValueError("PLY has no vertex element")
    if not {"x", "y", "z"}.issubset({name for name, _ in vertex_properties}):
        raise ValueError("PLY vertex element must contain x, y, and z fields")

    return {
        "path": path,
        "format": fmt,
        "vertex_count": vertex_count,
        "vertex_properties": vertex_properties,
        "header_size": header_size,
    }


def vertex_dtype(info: dict) -> np.dtype:
    if info["format"] == "binary_big_endian":
        endian = ">"
    elif info["format"] == "binary_little_endian":
        endian = "<"
    else:
        endian = "="

    return np.dtype([
        (name, f"{endian}{PLY_SCALAR_TYPES[ply_type]}")
        for name, ply_type in info["vertex_properties"]
    ])


def read_vertices(info: dict) -> np.ndarray:
    dtype = vertex_dtype(info)
    path = info["path"]
    count = info["vertex_count"]

    if info["format"] == "ascii":
        data = np.genfromtxt(
            path,
            dtype=dtype,
            skip_header=header_line_count(path),
            max_rows=count,
        )
        return np.atleast_1d(data)

    with path.open("rb") as f:
        f.seek(info["header_size"])
        data = np.fromfile(f, dtype=dtype, count=count)

    if data.shape[0] != count:
        raise ValueError(f"Expected {count} vertices, found {data.shape[0]}")
    return data


def header_line_count(path: Path) -> int:
    with path.open("rb") as f:
        for i, line in enumerate(f, start=1):
            if line.strip() == b"end_header":
                return i
    raise ValueError(f"{path} ended before end_header")


def normalize(values: np.ndarray) -> np.ndarray:
    values = values.astype(np.float64, copy=False)
    finite = np.isfinite(values)
    out = np.zeros(values.shape, dtype=np.float64)
    if not np.any(finite):
        return out

    lo = float(np.percentile(values[finite], 2))
    hi = float(np.percentile(values[finite], 98))
    if hi <= lo:
        lo = float(np.min(values[finite]))
        hi = float(np.max(values[finite]))
    if hi <= lo:
        return out

    out[finite] = np.clip((values[finite] - lo) / (hi - lo), 0.0, 1.0)
    return out


def scalar_to_colors(values: np.ndarray) -> np.ndarray:
    t = normalize(values)
    # Lightweight blue -> teal -> green -> yellow ramp without matplotlib.
    return np.column_stack(
        (
            np.clip(1.6 * t - 0.25, 0.0, 1.0),
            np.clip(1.6 - np.abs(2.0 * t - 1.0), 0.0, 1.0),
            np.clip(1.25 - 1.5 * t, 0.0, 1.0),
        )
    )


def categorical_to_colors(values: np.ndarray) -> np.ndarray:
    labels = values.astype(np.int64, copy=False)
    colors = np.empty((labels.shape[0], 3), dtype=np.float64)

    valid = labels >= 0
    hashed = labels[valid].astype(np.uint64)
    hashed = (hashed * np.uint64(2654435761)) ^ (hashed >> np.uint64(16))
    colors[valid, 0] = ((hashed >> np.uint64(0)) & np.uint64(255)) / 255.0
    colors[valid, 1] = ((hashed >> np.uint64(8)) & np.uint64(255)) / 255.0
    colors[valid, 2] = ((hashed >> np.uint64(16)) & np.uint64(255)) / 255.0
    colors[~valid] = np.array([0.35, 0.35, 0.35])
    return colors


def rgb_colors(data: np.ndarray) -> np.ndarray | None:
    names = set(data.dtype.names or ())
    if not {"red", "green", "blue"}.issubset(names):
        return None
    colors = np.column_stack((data["red"], data["green"], data["blue"])).astype(np.float64)
    if np.nanmax(colors) > 1.0:
        colors /= 255.0
    return np.clip(colors, 0.0, 1.0)


def choose_color_field(data: np.ndarray, requested: str) -> str:
    names = set(data.dtype.names or ())
    if requested != "auto":
        return requested

    for candidate in AUTO_COLOR_PRIORITY:
        if candidate == "red_green_blue" and {"red", "green", "blue"}.issubset(names):
            return candidate
        if candidate == "z" or candidate in names:
            return candidate
    return "none"


def build_colors(data: np.ndarray, requested: str) -> tuple[np.ndarray | None, str]:
    color_field = choose_color_field(data, requested)
    names = set(data.dtype.names or ())

    if color_field in {"none", "off"}:
        return None, color_field
    if color_field == "red_green_blue":
        return rgb_colors(data), color_field
    if color_field not in names:
        raise ValueError(f"Field '{color_field}' is not present. Available fields: {sorted(names)}")
    if color_field in CATEGORICAL_FIELDS:
        return categorical_to_colors(data[color_field]), color_field
    return scalar_to_colors(data[color_field]), color_field


def main() -> int:
    args = parse_args()
    info = parse_ply_header(args.ply)
    data = read_vertices(info)
    names = data.dtype.names or ()

    if args.list_fields:
        for name in names:
            print(name)
        return 0

    try:
        import open3d as o3d
    except ImportError as exc:
        raise SystemExit(
            "Open3D is not installed. Install it with: python3 -m pip install open3d"
        ) from exc

    points = np.column_stack((data["x"], data["y"], data["z"])).astype(np.float64, copy=False)
    pcd = o3d.geometry.PointCloud()
    pcd.points = o3d.utility.Vector3dVector(points)

    colors, color_field = build_colors(data, args.color_by)
    if colors is not None:
        pcd.colors = o3d.utility.Vector3dVector(colors)

    if args.voxel_size > 0:
        pcd = pcd.voxel_down_sample(args.voxel_size)

    print(f"Opened: {args.ply}")
    print(f"Points: {len(pcd.points)}")
    print(f"Color:  {color_field}")

    vis = o3d.visualization.Visualizer()
    vis.create_window(window_name=args.ply.name)
    vis.add_geometry(pcd)
    render = vis.get_render_option()
    render.point_size = args.point_size
    render.background_color = np.array([0.04, 0.04, 0.04])
    vis.run()
    vis.destroy_window()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
